import { PERMISSIONS } from '../utils/accessControl'

/** Built-in gov dashboard widgets (data from /api/gov/dashboard/auto-fill) */
export const BUILTIN_WIDGETS = [
  {
    id: 'kpi-total-revenue',
    type: 'builtin-kpi',
    category: 'kpi',
    labelKey: 'customDashboard.widgets.totalRevenue',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { metric: 'marketAnalysis.totalRevenue', format: 'currency' },
    defaultLayout: { colSpan: 3, rowSpan: 1 },
  },
  {
    id: 'kpi-total-transactions',
    type: 'builtin-kpi',
    category: 'kpi',
    labelKey: 'customDashboard.widgets.totalTransactions',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { metric: 'marketAnalysis.totalTransactions', format: 'number' },
    defaultLayout: { colSpan: 3, rowSpan: 1 },
  },
  {
    id: 'kpi-total-volume',
    type: 'builtin-kpi',
    category: 'kpi',
    labelKey: 'customDashboard.widgets.totalVolume',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { metric: 'marketAnalysis.totalVolume', format: 'volume' },
    defaultLayout: { colSpan: 3, rowSpan: 1 },
  },
  {
    id: 'kpi-average-price',
    type: 'builtin-kpi',
    category: 'kpi',
    labelKey: 'customDashboard.widgets.averagePrice',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { metric: 'marketAnalysis.averagePrice', format: 'price' },
    defaultLayout: { colSpan: 3, rowSpan: 1 },
  },
  {
    id: 'chart-revenue-trends',
    type: 'builtin-chart',
    category: 'chart',
    labelKey: 'customDashboard.widgets.revenueTrends',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { chartKey: 'revenueSparkline', chartType: 'area', dataKey: 'value', xAxisKey: 'date' },
    defaultLayout: { colSpan: 6, rowSpan: 2 },
  },
  {
    id: 'chart-price-trends',
    type: 'builtin-chart',
    category: 'chart',
    labelKey: 'customDashboard.widgets.priceTrends',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { chartKey: 'priceTrends', chartType: 'line', dataKey: 'price', xAxisKey: 'date' },
    defaultLayout: { colSpan: 6, rowSpan: 2 },
  },
  {
    id: 'chart-transactions-type',
    type: 'builtin-chart',
    category: 'chart',
    labelKey: 'customDashboard.widgets.transactionsByType',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { chartKey: 'transactionsByType', chartType: 'bar', dataKey: 'value', xAxisKey: 'name' },
    defaultLayout: { colSpan: 6, rowSpan: 2 },
  },
  {
    id: 'chart-production-category',
    type: 'builtin-chart',
    category: 'chart',
    labelKey: 'customDashboard.widgets.productionByCategory',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { chartKey: 'productionByCategory', chartType: 'pie', dataKey: 'value', nameKey: 'name' },
    defaultLayout: { colSpan: 6, rowSpan: 2 },
  },
  {
    id: 'overview-users',
    type: 'builtin-overview',
    category: 'overview',
    labelKey: 'customDashboard.widgets.totalUsers',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { field: 'totalUsers', detailField: 'activeUsers30Days', detailLabelKey: 'dashboard.active30d' },
    defaultLayout: { colSpan: 3, rowSpan: 1 },
  },
  {
    id: 'overview-farms',
    type: 'builtin-overview',
    category: 'overview',
    labelKey: 'customDashboard.widgets.totalFarms',
    permission: PERMISSIONS.GOV_DASHBOARD,
    config: { field: 'totalFarms', detailField: 'totalInventory', detailLabelKey: 'dashboard.inventory', suffix: ' kg' },
    defaultLayout: { colSpan: 3, rowSpan: 1 },
  },
]

export const PREDEFINED_REPORT_WIDGETS = [
  { categoryId: 'sales', reportId: 'sales-trends', endpoint: 'getSalesTrends', labelKey: 'reportWidgets.salesTrends', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'sales', reportId: 'sales-by-category', endpoint: 'getSalesByCategory', labelKey: 'reportWidgets.salesByCategory', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'financial', reportId: 'revenue', endpoint: 'getRevenue', labelKey: 'reportWidgets.revenue', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'financial', reportId: 'profit-loss', endpoint: 'getProfitLoss', labelKey: 'reportWidgets.profitLoss', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'users', reportId: 'user-activity', endpoint: 'getUserActivity', labelKey: 'reportWidgets.userActivity', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'users', reportId: 'user-registrations', endpoint: 'getUserRegistrations', labelKey: 'reportWidgets.userRegistrations', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'products', reportId: 'top-products', endpoint: 'getTopProducts', labelKey: 'reportWidgets.topProducts', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'market', reportId: 'market-trends', endpoint: 'getMarketTrends', labelKey: 'reportWidgets.marketTrends', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'auctions', reportId: 'auction-revenue', endpoint: 'getAuctionRevenue', labelKey: 'reportWidgets.auctionRevenue', permission: PERMISSIONS.GOV_REPORTS },
  { categoryId: 'tenders', reportId: 'tender-activity', endpoint: 'getTenderActivity', labelKey: 'reportWidgets.tenderActivity', permission: PERMISSIONS.GOV_REPORTS },
]
